import React from 'react';

function downloadMarkdown(report) {
  const blob = new Blob([report.markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `bhuvan-${report.kind}-${report.job_id?.slice(0, 8) || 'report'}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Lightweight markdown renderer — headings, tables, bold, lists.
 *  Reports are generated by our own backend, so the input is trusted. */
function renderMarkdown(md) {
  const lines = md.split('\n');
  const out = [];
  let table = null;

  const flushTable = () => {
    if (!table) return;
    out.push(
      <table key={out.length} className="report-table">
        <tbody>
          {table.map((cells, r) => (
            <tr key={r}>
              {cells.map((c, i) =>
                r === 0
                  ? <th key={i}>{inline(c)}</th>
                  : <td key={i}>{inline(c)}</td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
    );
    table = null;
  };

  const inline = (text) => {
    const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
    return parts.map((p, i) => {
      if (p.startsWith('**')) return <strong key={i}>{p.slice(2, -2)}</strong>;
      if (p.startsWith('`')) return <code key={i}>{p.slice(1, -1)}</code>;
      return p;
    });
  };

  for (const line of lines) {
    if (line.startsWith('|')) {
      const cells = line.split('|').slice(1, -1).map((c) => c.trim());
      if (cells.every((c) => /^-+$/.test(c))) continue;
      table = table || [];
      table.push(cells);
      continue;
    }
    flushTable();

    if (line.startsWith('### ')) out.push(<h4 key={out.length}>{inline(line.slice(4))}</h4>);
    else if (line.startsWith('## ')) out.push(<h3 key={out.length}>{inline(line.slice(3))}</h3>);
    else if (line.startsWith('# ')) out.push(<h2 key={out.length}>{inline(line.slice(2))}</h2>);
    else if (line.startsWith('> ')) out.push(<blockquote key={out.length}>{inline(line.slice(2))}</blockquote>);
    else if (line.startsWith('- ')) out.push(<li key={out.length}>{inline(line.slice(2))}</li>);
    else if (line.startsWith('---')) out.push(<hr key={out.length} />);
    else if (line.trim()) out.push(<p key={out.length}>{inline(line)}</p>);
  }
  flushTable();
  return out;
}

export default function ReportModal({ report, onClose }) {
  if (!report) return null;
  return (
    <div className="report-modal-backdrop" onClick={onClose}>
      <div className="report-modal" onClick={(e) => e.stopPropagation()}>
        <header className="report-modal-header">
          <span className="report-modal-kind">{report.kind?.toUpperCase()} REPORT</span>
          <div className="report-modal-actions">
            <button onClick={() => downloadMarkdown(report)}>⬇ EXPORT .MD</button>
            <button onClick={() => window.print()}>⎙ PRINT / PDF</button>
            <button onClick={onClose}>✕</button>
          </div>
        </header>
        <div className="report-modal-body">{renderMarkdown(report.markdown)}</div>
      </div>
    </div>
  );
}
